import {createElement,type ComponentType,type ReactNode} from "react";
import type {ComponentRegistry} from "@agentreach/component-registry";
import {validateSurfaceSchema,type UISurfaceComponent,type UISurfaceSchema} from "@agentreach/ui-schema";
export type SurfaceData=Readonly<Record<string,unknown>>;
export type SurfaceCommand=(payload:{command:string;event:string;componentId:string})=>void|Promise<void>;
export type RuntimeComponentProps=Readonly<Record<string,unknown>>&{actions?:Readonly<Record<string,()=>void>>};
export type RuntimeComponent=ComponentType<RuntimeComponentProps>;
export interface PreparedComponent{schema:UISurfaceComponent;component:RuntimeComponent;props:Readonly<Record<string,unknown>>}
export type PrepareResult={success:true;schema:UISurfaceSchema;components:readonly PreparedComponent[]}|{success:false;issues:readonly {path:string;message:string}[]};
const blocked=new Set(["__proto__","prototype","constructor"]);
export function readDataPath(data:SurfaceData,path:string,fallback?:unknown):unknown{const parts=path.split(".").filter(Boolean);if(!parts.length||parts.some(part=>blocked.has(part)))return fallback;let value:unknown=data;for(const part of parts){if(typeof value!=="object"||value===null||Array.isArray(value)||!Object.prototype.hasOwnProperty.call(value,part))return fallback;value=(value as Record<string,unknown>)[part]}return value??fallback}
function isVisible(item:UISurfaceComponent,data:SurfaceData){if(item.visible===false)return false;const rule=item.visibility;if(!rule)return true;const value=readDataPath(data,rule.when);if(rule.exists!==undefined&&(value!==undefined)!==rule.exists)return false;return rule.equals===undefined||Object.is(value,rule.equals)}
function bindActions(item:UISurfaceComponent,events:readonly string[],command?:SurfaceCommand){if(!item.actions?.length)return undefined;const actions:Record<string,()=>void>={};for(const binding of item.actions){if(!events.includes(binding.event))throw new Error(`event ${binding.event} is not declared by ${item.componentId}`);if(binding.approval==="strong"&&!binding.command.startsWith("protected."))throw new Error(`strong approval command must use protected namespace: ${binding.command}`);actions[binding.event]=()=>{void command?.({command:binding.command,event:binding.event,componentId:item.componentId})}}return actions}
export function prepareSurface(input:unknown,registry:ComponentRegistry<RuntimeComponent>,data:SurfaceData,command?:SurfaceCommand):PrepareResult{const checked=validateSurfaceSchema(input);if(!checked.success)return checked;try{const components=checked.value.components.filter(item=>isVisible(item,data)).map(item=>{const component=registry.resolve(item.componentId,checked.value.surface);const manifest=registry.manifest(item.componentId);if(!manifest)throw new Error(`missing manifest: ${item.componentId}`);const bound=Object.fromEntries(Object.entries(item.bindings??{}).map(([prop,binding])=>[prop,readDataPath(data,binding.source,binding.fallback)]));return{schema:item,component,props:{...(item.props??{}),...bound,actions:bindActions(item,manifest.events,command)}}});return{success:true,schema:checked.value,components}}catch(error){return{success:false,issues:[{path:"$.components",message:error instanceof Error?error.message:"surface preparation failed"}]}}}
export function SurfaceRuntime({schema,registry,data,command,fallback,className,ariaLabel}:{schema:unknown;registry:ComponentRegistry<RuntimeComponent>;data:SurfaceData;command?:SurfaceCommand;fallback?:ReactNode;className?:string;ariaLabel?:string}){const result=prepareSurface(schema,registry,data,command);if(!result.success)return createElement("section",{className:`surface-runtime-error${className?` ${className}`:""}`,role:"status","aria-label":ariaLabel,"data-surface-error":true},fallback??"界面暂时不可用");return createElement("section",{className:`surface-runtime layout-${result.schema.layout}${className?` ${className}`:""}`,"aria-label":ariaLabel,"data-surface-id":result.schema.id,"data-surface-version":result.schema.version},...result.components.map(item=>createElement("div",{key:item.schema.id,className:`surface-zone zone-${item.schema.zone}`,"data-component-id":item.schema.componentId},createElement(item.component,item.props))))}
